#! python3
# This program extracts locations from excel
# and outputs GPS coordinates from latlong.net

import openpyxl, pyperclip, requests, os, bs4

from selenium import webdriver
import time

#Open Firefox browser and Procore.com
driver = webdriver.Firefox()
driver.get('https://app.procore.com/731567/project/submittal_logs/list?page=1&view=list&filters%5Bresponse_id%5D%5B%5D=6636482&filters%5Bresponse_id%5D%5B%5D=6636489&sort%5Battribute%5D=number&sort%5Bdirection%5D=desc&per_page=150')
time.sleep(30)


#Get all links from a webpage
for a in driver.find_elements_by_xpath('.//a'):
    print(a.get_attribute('href'))
